name: Continuous release to pkg.pr.new

on:
  push:
    branches: 
      - main
    tags:
      - '!**'
  pull_request:
    types: [closed]
    branches: 
      - main

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Release
        run: npx pkg-pr-new publish
    
